name: CI

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the top of every hour
  workflow_dispatch:     # Allows manual triggering
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry

      - name: Install project dependencies
        run: poetry install

      - name: Run Pytest with Allure
        env:
            WOLFRAM_APP_ID: ${{ secrets.WOLFRAM_APP_ID }}
        run: |
          poetry run pytest --alluredir=allure-results
      - name: Generate Allure HTML Report
        run: |
          pip install allure-python-commons
          wget https://github.com/allure-framework/allure2/releases/download/2.34.1/allure-2.34.1.tgz
          tar -xzf allure-2.34.1.tgz
          ./allure-2.34.1/bin/allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
