name: CI

on:
  schedule:
    - cron: '0 * * * *'  # Hourly
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Package & Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

    - name: Install Allure CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jre
        curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/download/2.33.0/allure-2.33.0.tgz
        tar -zxvf allure.tgz -C /opt/
        sudo ln -s /opt/allure-2.33.0/bin/allure /usr/bin/allure

      - name: Run Pytest with Allure
        env:
            WOLFRAM_APP_ID: ${{ secrets.WOLFRAM_APP_ID }}
          mkdir -p allure-results
          poetry run pytest tests --alluredir=allure-results
          allure generate --single-file allure-results -o allure-report --clean

      - name: Upload Allure report HTML as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/index.html