name: CI for voxsynth

on:
  push:
    branches: [ "main", "voice-recorder" ]
  pull_request:
    branches: [ "main", "voice-recorder" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --with dev
    - name: Install Allure CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jre
        curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/download/2.33.0/allure-2.33.0.tgz
        tar -zxvf allure.tgz -C /opt/
        sudo ln -s /opt/allure-2.33.0/bin/allure /usr/bin/allure
    - name: Run tests with pytest and generate Allure results
      run: |
        mkdir -p allure-results
        poetry run pytest tests --alluredir=allure-results
        allure generate --single-file allure-results -o allure-report --clean
    - name: Upload Allure report HTML as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report/index.html